chore: use git status --porcelain

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -38,22 +38,18 @@ commands:
       - run: |
           source ~/.bashrc
           npx auto shipit --only-graduate-with-release-label -vv
-  dry_run:
-    description: Perform Auto shipit --dry-run
+  check_branch_status:
+    description: "Check if the branch is clean after the build"
     steps:
-      - attach_workspace:
-          at: ~/tools
-
-      - restore_cache:
-          keys:
-            - v1-bazel-cache-core-{{ .Branch }}-{{ .Revision }}
-            - v1-bazel-cache-core-{{ .Branch }}
-            - v1-bazel-cache-core-main
-
-      - run: |
-          echo 'export GH_TOKEN=${GH_TOKEN}' >> ~/.bashrc
-          source ~/.bashrc
-          npx auto shipit --dry-run
+      - run:
+          name: Check branch status
+          command: |
+            if [[ -n "$(git status --porcelain)" ]]; then 
+              echo "Error: The branch is not clean after the build. Please commit."
+              exit 1
+            else
+              echo "The branch is clean after the build."
+            fi
 
 jobs:
   setup:
@@ -101,7 +97,7 @@ jobs:
           root: .
           paths:
             - .
-      - dry_run
+      - check_branch_status
 
   test:
     executor: base
